runtime: python39

handlers:
- url: /.*
  script: auto

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: ""\\wsl.localhost\Ubuntu\home\benjaminbhk\.config\gcloud\legacy_credentials\benjamin.barre@gmail.com\democnndigitsrecognitionbenbhk-460355146889.json""
